// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfkY0wBrHnVydJkwfpUdDdZzyEq0oBqGI',
    appId: '1:402123760803:web:e58e2f17526cbc0a9a0b16',
    messagingSenderId: '402123760803',
    projectId: 'notesapp-cb350',
    authDomain: 'notesapp-cb350.firebaseapp.com',
    storageBucket: 'notesapp-cb350.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0nEJVQ60rJfxAY75wdS33uSRe-x9FJjg',
    appId: '1:402123760803:android:95016981d31aea489a0b16',
    messagingSenderId: '402123760803',
    projectId: 'notesapp-cb350',
    storageBucket: 'notesapp-cb350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtQqZlHoBC_Glt6ZyMw0F8s-f-UdXKY38',
    appId: '1:402123760803:ios:9d96424027013d789a0b16',
    messagingSenderId: '402123760803',
    projectId: 'notesapp-cb350',
    storageBucket: 'notesapp-cb350.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtQqZlHoBC_Glt6ZyMw0F8s-f-UdXKY38',
    appId: '1:402123760803:ios:e7f167f738ffcd529a0b16',
    messagingSenderId: '402123760803',
    projectId: 'notesapp-cb350',
    storageBucket: 'notesapp-cb350.appspot.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
